# Generated by Django 5.1.3 on 2025-02-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bioText',
            field=models.TextField(blank=True, default='', max_length=150, null=True),
        ),
    ]
