# Generated by Django 5.1.3 on 2025-03-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bioText',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
    ]
