# Generated by Django 5.1.3 on 2025-02-20 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0004_alter_profile_email'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relate', models.CharField(choices=[('LKE', 'Like'), ('SVE', 'Save'), ('SHR', 'Share')], max_length=5)),
                ('timestamp', models.TimeField()),
                ('blogid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.blog')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.profile')),
            ],
        ),
    ]
